language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 0gqoj33wRGsLtDqsI11b8ozPRZRdlsCPDocIY8mZhA4kmNON7C5WN1Le33nofAjozxXmMmeRdQgn3DVvZGbnqhoYQRPHAciN+0KLr5D6829ImwLdf3lG+kO7U5kDLEfSTJlPyP3XTRoYQHcwD5TCsBe/FEuqvKk1bmnVQkRX4AQo/6+IYDwzwsj0GiFt2T2hGFB1tWhCHMmwAkalKzwHm23EVOjGJsYRvc2I1pGOHtyFcXX0HsA9cpVx14pFtd74bFQ+pAYW0ZOGYC0RMTJbxRcLUlUz+cmKEScE6+SElcawWRB1qapF8IiWRMUmPts/cLISW6FHg+dHJzg6cbMw6kjRAUkUXNWIWQF8siAEuLWDXrSo1CCLUG1eCogA4TORsaCFHQkQIPKt5iEL1KYdjrFXjztAjXvELO6mQ4lkEjUy/M9nyO3X3pi7Kqq8wnVPd2/o8gFaxarIa8stgFft0GDt7Stv0Hjw3MAdxaxTvvq/vblDE0QPagRTC2StRrQwUqwMRHf+8MLZW4lxgWsp9YCk9LYfH8gjE1YdjTPbhd4F+5MUQXRF6G9h+iZ5VLQ8dfqnG9s5jPrOJJ5th6aJemqSyOD6YGywx9zFuYXIEFCRZ+Rw2vbRqIZXBJrM8hsx8JqXYkQOEsOUYNSY8d8jR5L59PDFSAY/sygI00xOK7w=
  app: glacial-basin-87239
  on:
    repo: Shubanshii/MusicianShip2
